name: Check Nix Rebuild

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_version: latest
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.nixos.config.system.build.toplevel
