name: Check Nix Rebuild

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_version: latest
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Nixos rebuild configurations
        run: nixos-rebuild --flake .#nixos
