name: Check Nix Format

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_version: latest
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Install fd
        run: nix profile install nixpkgs#fd
      - name: Install nixfmt
        run: nix-env -iA nixos.nixfmt-rfc-style
      - name: Check Nix format with nixfmt
        run: |
          set -euo pipefail
          fd --extension nix --exec nixfmt --check {}
