name: Check Nix Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            - name: nix flake check
      - name: nix flake check
        run: nix flake check

      - name: nix flake build
        run: nix build .#nixosConfigurations.nixos.config.system.build.vm
