name: Check Nix Format

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_version: latest
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Install dependencies
        run: |
          nix profile install nixpkgs#fd
          nix profile install nixpkgs#nixfmt-rfc-style

      - name: Check Nix formatting
        run: |
          set -euo pipefail

          fd . -name "*.nix" | while read file; do
            echo "Tests $file"
            if ! nixfmt --check "$file"; then
              echo "❌ ERROR $file"
              echo "::error file=$file::run nixfmt pls!!!"
              exit 1
            fi
          done
          echo "✅"
